### ISSUE TITLE
test_babai fails on all architectures but amd64

### ISSUE THREAD

**Issue by txgk** [fplll/fplll#500] opened 2022-12-25 12:51 UTC
When upgrading fplll package in Alpine Linux repositories to 5.4.3 version I ran into a failing test `test_babai` which successfully runs only on amd64 (x86_64).

Upgrade merge request: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/42620
aarch64 build log: https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/934088
armhf build log: https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/934090
armv7 build log: https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/934089
ppc64le build log: https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/934087
s390x build log: https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/934086
x86 build log: https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/934085

Can you provide a patch which fixes this regression?

**Comment by SnarkBoojum** [comment] 2022-12-28 13:14
I confirm the issue on Debian; you can access the logs [here](https://buildd.debian.org/status/package.php?p=fplll).

**Comment by malb** [comment] 2022-12-29 16:43
Thanks for reporting these. This should be now fixed in master. I assume for you to test it you'd prefer a new release cut?

**Comment by txgk** [comment] 2022-12-29 17:39
If that's okay with you, it would be cool. Bumping a version is easier than applying patch :)

**Comment by SnarkBoojum** [comment] 2022-12-29 17:42
I uploaded 5.4.3-2 which should appear in the logs in a few hours, with just the simple commit as a patch.

I suggest to wait until the fix is confirmed before cutting a new version.

**Comment by joerowell** [comment] 2022-12-29 18:05
Thanks -- I only tested the patch on ARM and x86, so waiting for the other
platforms is a good idea in case I missed something obvious.

**Comment by musicinmybrain** [comment] 2022-12-29 22:06
I’m the primary maintainer of the [Fedora Linux package](https://src.fedoraproject.org/rpms/libfplll). I’m currently verifying the patch on x86_64, i686, ppc64le, s390x, aarch64, and armhfp/armv7hl. I’ll follow up when the test builds finish.

Can you please have a look at https://github.com/fplll/fplll/issues/502 before cutting a new release?

**Comment by joerowell** [comment] 2022-12-29 22:14
I think the patch needs an update for ppc etc -- we should also cover the
case that long double is 128 bits, which I forgot earlier.

I'll do that tomorrow, and hopefully that'll fix all of the builds.

**Comment by musicinmybrain** [comment] 2022-12-29 22:25
> […] I’m currently verifying the patch on x86_64, i686, ppc64le, s390x, aarch64, and armhfp/armv7hl.

The builds for x86_64 and i686 succeeded.

----

The build for armhfp/armv7hl failed in `configure`:

```
checking whether the C compiler works... no
configure: error: in `/builddir/build/BUILD/fplll-5.4.3':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

I don’t care about this failure since that architecture is retired in Fedora 37 and later, and I’m not planning to update fplll in Fedora 36. Still, I’ll see if I can find out what was in `config.log`.

----

The build for ppc64le failed with the error below.

Note that ppc64le [has 128-bit `long double`](https://fedoraproject.org/wiki/Changes/PPC64LE_Float128_Transition) in Fedora.

```
FAIL: test_babai
================
n:10, bits: 70, shouldfail:1
t:[2304979229261421498992 0 0 0 0 0 0 0 0 0 0]
w:[2304979229261421498992 1 0 1 0 1 1 0 0 1 1]
FAIL test_babai (exit status: 255)
```

----

The aarch64 build also failed for me:

```
FAIL: test_babai
================
n:10, bits: 70, shouldfail:1
t:[2304979229261421498992 0 0 0 0 0 0 0 0 0 0]
w:[2304979229261421498992 1 0 1 0 1 1 0 0 1 1]
FAIL test_babai (exit status: 255)
```

----

So did `s390x`:

```
FAIL: test_babai
================
n:10, bits: 70, shouldfail:1
t:[2304979229261421498992 0 0 0 0 0 0 0 0 0 0]
w:[2304979229261421498992 1 0 1 0 1 1 0 0 1 1]
FAIL test_babai (exit status: 255)
```

**Comment by musicinmybrain** [comment] 2022-12-30 14:50
With #504, tests now pass on all current Fedora architectures (x86_64, i686, ppc64le with 128-bit `long double`, s390x, and aarch64), plus armhfp/armv7hl, which was retired after Fedora 36.

**Comment by txgk** [comment] 2022-12-30 15:28
> With #504, tests now pass on all current Fedora architectures (x86_64, i686, ppc64le with 128-bit `long double`, s390x, and aarch64), plus armhfp/armv7hl, which was retired after Fedora 36.

On Alpine Linux not all architectures passed tests with the #504 - [x86 failed test_babai again](https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/937611)

**Comment by joerowell** [comment] 2022-12-30 15:55
> On Alpine Linux not all architectures passed tests with the #504 - [x86 failed test_babai again](https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/937611)

Ah: ```x86```, not ```x86_64```. Let me try and fix that too: thanks for your patience!

**Comment by joerowell** [comment] 2022-12-30 19:00
I can't replicate the failure on the most recent version of Alpine for ```x86```. I've tried #504 in both a VM and the official ```x86``` Docker instance, but the tests still pass. 

Would it be possible to get the ```tests/test-suite.log``` from the failed run? That might help us pinpoint exactly what's causing this.

**Comment by txgk** [comment] 2022-12-30 20:04
I don't have direct access to builders but I did `cat` this log into build log with package recipe. Kinda dirty but here it is:
```
=======================================
   fplll 5.4.3: tests/test-suite.log
=======================================

# TOTAL: 15
# PASS:  14
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_babai
================

n:10, bits: 110, shouldfail:0
t:[2012369290890635300733361896222358 0 0 0 0 0 0 0 0 0 0]
w:[2012369290890635432020082235606000 -152682956321348671 64055602872015056 -18490701559500375 -43166511640482841 74534945476387953 -6865320092144422 10830115531037097 -34527528686759187 54669572203368407 113928152583964593]
FAIL test_babai (exit status: 255)
```

**Comment by joerowell** [comment] 2022-12-30 20:15
Thanks! That's exactly what I needed.

**Comment by joerowell** [comment] 2022-12-31 14:08
> I don't have direct access to builders but I did `cat` this log into build log with package recipe. Kinda dirty but here it is:
> 
> ```
> =======================================
>    fplll 5.4.3: tests/test-suite.log
> =======================================
> 
> # TOTAL: 15
> # PASS:  14
> # SKIP:  0
> # XFAIL: 0
> # FAIL:  1
> # XPASS: 0
> # ERROR: 0
> 
> .. contents:: :depth: 2
> 
> FAIL: test_babai
> ================
> 
> n:10, bits: 110, shouldfail:0
> t:[2012369290890635300733361896222358 0 0 0 0 0 0 0 0 0 0]
> w:[2012369290890635432020082235606000 -152682956321348671 64055602872015056 -18490701559500375 -43166511640482841 74534945476387953 -6865320092144422 10830115531037097 -34527528686759187 54669572203368407 113928152583964593]
> FAIL test_babai (exit status: 255)
> ```

This should now be fixed in the most recent patch. Could you confirm please? I've tried this on my Alpine Linux VM and it passes there, so hopefully it also works for you too :)

**Comment by txgk** [comment] 2022-12-31 14:34
It's passes on builders now too, thank you.

**Comment by musicinmybrain** [comment] 2022-12-31 15:09
The updated patch continues to work for me in Fedora-land.

**Comment by SnarkBoojum** [comment] 2023-01-03 13:18
Sorry, I wasn't available for more testing ; does that mean you're ready to cut a new version?

**Comment by malb** [comment] 2023-01-03 14:00
Yep, I hope to do that this week.

**Comment by malb** [comment] 2023-01-05 14:51
This seems to be fixed.

**Closed by malb** 2023-01-05 14:51 UTC
