### ISSUE TITLE
Fix ARM-specific problem with new multicore code in fplll 5.3.x

### ISSUE THREAD

**Issue by slel** [fplll/fplll#432] opened 2020-06-24 15:52 UTC
An ARM-specific problem with new multicore code in fplll 5.3.x
is suspected in a discussion on the sage-release mailing list,
on 2020-01-26, by Jaap Spies, Dima Pasechnik, Martin Albrecht.

Jaap Spies reports that on Raspberry Pi, Sage 9.1.beta0 builds
but Sage 9.1.beta1 does not, and Dima Pasechnik and
Martin Albrecht help pinpoint the problem.

See this post and the following ones in the sage-release thread:

- https://groups.google.com/d/msg/sage-release/xcGXMuHuEOw/Mq25b-13DgAJ

**Comment by cr-marcstevens** [comment] 2020-06-24 15:58
This looks related to #418 and appeared to be solved at the time.
Can you confirm the suggested fix in there does / doesn't work?

**Comment by slel** [comment] 2020-06-24 16:33
Oh, I missed that, as well as this Sage ticket:

- https://trac.sagemath.org/ticket/29091

where someone will hopefully confirm things work now.

**Comment by cr-marcstevens** [comment] 2020-06-24 16:55
If I understand correctly then part of the issue now is that there isn't an official fplll release containing the fix?

**Comment by mkoeppe** [comment] 2020-06-25 19:26
> If I understand correctly then part of the issue now is that there isn't an official fplll release containing the fix?

That's right. The issue is confirmed to be fixed in fplll master. All we need on the SageMath side is a new release.

**Comment by mkoeppe** [comment] 2020-06-25 19:28
See also #433, which contributes a CI script to fplll using Sage, providing broader portability testing including `raspbian-buster-armhf`

**Comment by cr-marcstevens** [comment] 2020-06-26 14:53
I'll defer to @malb who is the main person to make a new release. Thanks for reporting!

**Comment by malb** [comment] 2020-11-27 11:16
This seems resolved for now. CI can be a separate issue

**Closed by malb** 2020-11-27 11:16 UTC
