### ISSUE TITLE
libfplll.so not linked to libpthread

### ISSUE THREAD

**Issue by antonio-rojas** [fplll/fplll#395] opened 2019-11-23 20:45 UTC
In 5.3.0, libfplll is being compiled with threads, but the output library is not linked to libpthread. This results in undefined symbol errors when trying to compile stuff against it:
```
configure:15450: g++ -o conftest -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -I/usr/include/cxsc -D_FORTIFY_SOURCE=2   -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/build/gap/src/gap-4.10.2/tmp-install -lgap   conftest.cpp  -lfplll -lgmp >&5
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib/libfplll.so: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
```

**Comment by malb** [comment] 2019-11-24 10:52
As far as  I can tell, we do link against pthreads 
```
libfplll_la_CXXFLAGS=$(PTHREAD_CFLAGS)

EXTRA_libfplll_la_SOURCES= svpcvp.cpp
libfplll_la_LIBADD=$(LIBGMP) -lmpfr $(LIBQD_LIBADD) $(PTHREAD_LIBS)
libfplll_la_LDFLAGS=-no-undefined -version-info @FPLLL_LT_CURRENT@:@FPLLL_LT_REVISION@:@FPLLL_LT_AGE@ $(PTHREAD_CFLAGS)
```

but we didn't update `fplll.pc` to include the pthread stuff. Would that solve your issue?

**Comment by antonio-rojas** [comment] 2019-11-24 11:11
It is not linking for me:
```
> LANG=C readelf -d /usr/lib/libfplll.so
Dynamic section at offset 0xe5de20 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libqd.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libmpfr.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgmp.so.10]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x000000000000000e (SONAME)             Library soname: [libfplll.so.6]
[...]
```
In the Makefile, PTHREAD_LIBS is empty:
``` 
PTHREAD_CFLAGS = -pthread
PTHREAD_LIBS = 
```
For the same reason, your change to the pc file doesn't make any difference

**Comment by malb** [comment] 2019-11-24 11:16
AFAIK, on Linux (with GCC?) you don't need to link to libpthread. Instead, `-pthread` is passed as a `CFLAG`. So I think the output above is as expected.

**Comment by antonio-rojas** [comment] 2019-11-24 11:29
You certainly need to link to libpthread. What happens is that *if* you use gcc to compile and pass -pthread to CFLAGS, gcc automatically knows to link to libpthread and you don't need to do it explicitely. This does not work if you use libtool to compile (as you're doing in fplll) since libtool ignores some cflags by design. So in that case you need to link to libpthread explicitely by passing -lpthread to the linker.

**Comment by cr-marcstevens** [comment] 2019-11-24 11:45
We're using `AX_PTHREAD` ( https://www.gnu.org/software/autoconf-archive/ax_pthread.html ) in configure to find out `PTHREAD_CFLAGS` and `PTHREAD_LIBS`.
Can you share the output of fplll `configure`?

**Comment by antonio-rojas** [comment] 2019-11-24 12:11
The relevant part is:
```
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking that generated files are newer than configure... done
```
What seems to be happening is: configure checks that it works fine with only -pthread in CFLAGS (since the test program is compiled with the gcc command) so it decides it's not necessary to add anything to PTHREAD_LIBS, but this doesn't work when compiling fplll with the libtool command.

Also, this works fine when using ax_pthread.m4 from the latest autoconf-archive version 2019.01.06, so it may simply be a matter of updating the shipped ax_pthread.m4

**Comment by cr-marcstevens** [comment] 2019-11-25 10:37
PR #396 also updates `ax_pthread.m4` to latest version.
Although I couldn't really spot a difference in the updated `ax_pthread.m4` that explains why this is a solution.

I also created a PR #397 that checks all autoconf-archive `m4/*.m4` files for a newer version automatically during `make check-style`,
since the last two issues were both caused by an older version of such files.

**Comment by antonio-rojas** [comment] 2019-11-25 11:28
> PR #396 also updates `ax_pthread.m4` to latest version.
> Although I couldn't really spot a difference in the updated `ax_pthread.m4` that explains why this is a solution.

Yeah, sorry, that doesn't actually help. It seems I checked the binaries (which are linked to libpthread), but the library is still not.

See [1][2][3] for an overview of the issue with libtool and pthread. 
[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25460
[2] https://bugzilla.redhat.com/show_bug.cgi?id=661333
[3] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=468555

**Comment by cr-marcstevens** [comment] 2019-11-25 13:32
I just pushed a change to #396  to `m4/ax_pthread.m4` that for gcc & clang first tries `CFLAGS='-pthread'` and `LIBS='-lpthread'`, which should pass and fix this issue.
Can you confirm?

I'm slightly afraid this might break `m4/ax_pthread.m4`'s solution for rather special cases of C compilers and OSes. But our project targets C++11 compatible compilers anyway.

**Comment by antonio-rojas** [comment] 2019-11-25 17:25
> I just pushed a change to #396 to `m4/ax_pthread.m4` that for gcc & clang first tries `CFLAGS='-pthread'` and `LIBS='-lpthread'`, which should pass and fix this issue.
> Can you confirm?

Confirmed to work fine with this patch, thank you!

**Comment by cr-marcstevens** [comment] 2019-11-25 17:32
Great! Thanks for posting the issue & helping fix it!

**Comment by cr-marcstevens** [comment] 2019-12-05 08:46
Fix merged, so closing.

**Closed by cr-marcstevens** 2019-12-05 08:46 UTC
